plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/cesarecaesar/Documents/JCProductLab/perfil-busqueda-trabajo/portafolio/portafolio/V3/portfolio"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]